format_version: v1.0
type: UniqueComponent
attributes: {id: lib_emulated_eeprom}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_EEPROM_LOGICAL_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '1800'}
  - type: Hex
    attributes: {id: EEPROM_EMULATOR_EEPROM_START_ADDRESS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '258048'}
  - type: Boolean
    attributes: {id: EEPROM_EMULATOR_IS_DEPENDENCY_SATISFIED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: 'true'}
  - type: Boolean
    attributes: {id: EEPROM_EMULATOR_MAIN_ARRAY_ENABLED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: 'true'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_MAIN_ARRAY_NUM_PHYSICAL_PAGES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '64'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_MAIN_ARRAY_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '262144'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_MAIN_ARRAY_START_ADDR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '0'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_NUM_LOGICAL_PAGES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '30'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_NUM_PHYSICAL_PAGES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '64'}
  - type: String
    attributes: {id: EEPROM_EMULATOR_NVM_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: NVMCTRL}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_PAGES_PER_ROW}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '4'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_PAGE_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '64'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_ROW_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '256'}
  - type: Boolean
    attributes: {id: EEPROM_EMULATOR_RWWEE_ENABLED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: 'false'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_RWWEE_NUM_PHYSICAL_PAGES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '128'}
  - type: Integer
    attributes: {id: EEPROM_EMULATOR_RWWEE_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '8192'}
  - type: Hex
    attributes: {id: EEPROM_EMULATOR_RWWEE_START_ADDRESS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_emulated_eeprom, value: '4194304'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: lib_emulated_eeprom_MEMORY_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: nvmctrl}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NVMCTRL_MEMORY}
- type: ElementPosition
  attributes: {x: '507', y: '153', id: lib_emulated_eeprom}
